services:
  app:
    build: .
    container_name: player_review_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/player_review?schema=public
    networks:
      - player_review_network

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: player_review
    ports:
      - "5432:5432"
    networks:
      - player_review_network

networks:
  player_review_network:
    driver: bridge
